### ISSUE TITLE
Modificar el readme

### ISSUE THREAD

**Issue by cmonsalvec** [boscoandorg/text-analytics#4]
Por favor modificar el readme a la versión que hemos previamente acordado

**Comment by Boscoand** [comment]
@cmonsalvec se ha verificado que el readme requiere una modificación.

**Comment by Boscoand** [comment]
@DarNtn verificar por favor la solicitud planteada por @cmonsalvec y efectuar el análisis del impacto que tendría esta modificación en el proyecto.

**Comment by DarNtn** [comment]
El cambio requerido no representa ningún inconveniente en el desarrollo del proyecto, se procederá a realizar las actualizaciones solicitadas.

**Comment by DarNtn** [comment]
Las modificaciones en el readme han sido realizadas. 

@dguizado realizar las pruebas de sistema e integración del nuevo cambio.

**Comment by dguizado** [comment]
Pruebas del sistema e integración han sido realizadas

**Comment by dguizado** [comment]
Pruebas de aceptación

- [ ] Modificación realizada en el readme. 

Por favor aceptar @cmonsalvec los cambios

**Comment by dguizado** [comment]
Actividades se han completado con éxito, se va a realizar el merge de la [rama](https://github.com/boscoandorg/text-analytics/tree/modificar_readme) a máster. Luego se cerrará este issue
